import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  //
  // Note for anyone reaching for .eslintignore: it does nothing. ESLint 9
  // removed it, and a file of that name would sit in the repo looking load
  // bearing while being read by nothing. Ignores live here.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Build output of the SDK package, checked in so the tarball can be
    // inspected without a build step. It is generated by tsup from
    // packages/sdk/src, which IS linted; linting the bundle instead reports
    // problems in code nobody wrote and nobody can fix at the source shown.
    // packages/ is excluded from tsconfig for the same reason.
    "packages/*/dist/**",

    // A superseded single-file prototype of the whole app, kept for reference.
    // It is not imported, not built and not deployed; nothing in app/ or lib/
    // reaches into it.
    "prototype/**",
  ]),
]);

export default eslintConfig;
